CPP=g++
CCFLAGS=-std=c++11
EXE=parserPhase2
SRC=src
INCLIDE=-I include
objects=Expr.o ExprTree.o Program.o parser.o main.o

all: $(EXE)

%.o: $(SRC)/%.cpp
	$(CPP) -c $(CCFLAGS) $(INCLUDE) $< -o $@

$(EXE): $(objects)
	$(CPP) $(CCFLAGS)  -o $(EXE)
	$(CPP) $(CCFLAGS) parser.o 

clean:
	rm *.o
